"""
Multitenancy support for tasks

Revision ID: 81d53059a163
Revises: f50ad706c9c7
Create Date: 2019-03-08 17:30:52.377791

"""

# revision identifiers, used by Alembic.
revision = '81d53059a163'
down_revision = 'f50ad706c9c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tes_task', sa.Column('tenant_id', sa.String(length=64), nullable=True))
    op.add_column('tes_task', sa.Column('user_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tes_task', 'user_id')
    op.drop_column('tes_task', 'tenant_id')
    # ### end Alembic commands ###
