"""
Add the task_info table

Revision ID: f50ad706c9c7
Revises: 1fb7c6da302
Create Date: 2018-11-16 12:16:53.180442

"""

# revision identifiers, used by Alembic.
revision = 'f50ad706c9c7'
down_revision = '1fb7c6da302'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils
import uuid


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tes_task_info',
                    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4, nullable=False),
                    sa.Column('backend_id', sa.String(length=64), nullable=False),
                    # sa.Column('task_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('task_json', sqlalchemy_utils.types.JSONType(), nullable=True),
                    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('user', sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user', 'created_ts',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'created_ts',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False
                    )
    op.drop_column('user', 'updated_ts')
    op.drop_table('tes_task_info')
    # ### end Alembic commands ###
